config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :pets do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :pets
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :address, :bio, :first_name, :last_name, :email, :encrypted_password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :address, :bio, :first_name, :last_name, :email, :encrypted_password])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_pet, only: [:new, :create]
  before_action :set_booking, only: [:show]

  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking)
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new(start_date: Date.today, end_date: Date.today, accepted: false)
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.pet = @pet
    authorize @booking

    if @booking.save
      redirect_to user_path(current_user), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    authorize @booking
  end

  def accept
    @booking.accepted = true
    @booking.save
    redirect_to @booking.pet, notice: 'Booking was accepted.'
  end

  def reject
    @booking.accepted = false
    @booking.save
    redirect_to @booking.pet, notice: 'Booking was rejected.'
  end

  def edit
    authorize @booking
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :pet_id, :user_id, :accepted)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
    @pets = policy_scope(Pet)
    if params[:query].present?
      @pets = Pet.where("species ILIKE ?", "%#{params[:query]}%")
    else
      @pets = Pet.all
    end
  end

  def show
    authorize @pet
    @pet_markers = {
        lat: @pet.user.latitude,
        lng: @pet.user.longitude,
        # info_window_html: render_to_string(partial: "info_window", locals: {pet: @pet}),
        marker_html: render_to_string(partial: "pet_marker")
    }

  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def edit
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    if @pet.save
      redirect_to @pet, notice: "Your pet was successfully added."
    else
      render :new, status: :unprocessable_entity
    end
    authorize @pet
  end

  def update
    if @pet.update(pet_params)
      redirect_to @pet, notice: "Your pet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
    authorize @pet
  end

  def destroy
    @pet.destroy
    redirect_to pets_url, notice: "Your pet was successfully removed."
    authorize @pet
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :gender, :description, :special_notes, :price, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
    @markers = {
        lat: @user.latitude,
        lng: @user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: @user}),
        marker_html: render_to_string(partial: "marker")
    }

  end

  def index
    @users = Users.all
    # The `geocoded` scope filters only users with coordinates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container mb-5">
<div style="margin-top: 100px">
<h2>Book some time with <%= @pet.name %>! </h2>
<%= simple_form_for([@pet, @booking]) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :start_date %>

    <%= f.input :end_date %>

    <%= f.button :submit, 'Book', class: 'btn btn-primary' %>

  <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center text-white">

  <div class="p-4 pb-0">


      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
      <i class="fab fa-facebook-f"></i>
        </a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
      <i class="fab fa-twitter"></i>
        </a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
      <i class="fab fa-google"></i>
        </a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
      <i class="fab fa-instagram"></i>
      </a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
      <i class="fab fa-linkedin-in"></i>
        </a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i>
        </a>

  </div>

  <div class="text-center p-3" style="background-color: rgba (104, 179, 217, 1);">
    © by FauxPaws 2023
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container-fluid justify-content-between" style="height: 50px">
  <div class=" d-flex justify-content-center align-middle logo">
  <%= link_to "FauxPaws", root_path, class: "logo" %>

  </div>
    <form class="d-flex mx-auto">
    <%= form_with url: pets_path, method: :get, class: "form-control me-2" do %>
          <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a creature"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
    </form>

    <div class="blobby-icon">


    <% if current_user.nil? %>
        <%= link_to new_user_session_path do  %>
          <img class="rounded-circle mx-3" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1677670706/Blobby-04_cyelkq.png">
        <% end %>
      <% else %>
        <%= link_to user_path(current_user) do %>
          <img class="rounded-circle mx-3" src="https://res.cloudinary.com/dobohmdlf/image/upload/v1677670706/Blobby-04_cyelkq.png">
        <% end %>
    <% end %>

    </div>
  </div>
</nav>
<%# pundit %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetBuddy</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% unless current_page?(root_path) %>
    <%= render partial: "layouts/navbar" %>
    <%= render partial: "layouts/footer" %>
    <% end %>

  </body>
</html>

app/views/pages/home.html.erb
  <div class="full-page">

  <div class="d-flex align-items-center justify-content-center flex-column w-50 h-100" style="padding-left: 20%">
  <h1 class="mt-5"><strong>FauxPaws</strong></h1>
 <!-- <div class="d-flex mt-1"> -->
 <!--   <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light mx-2" %>-->
 <!--  <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-light mx-2" %>-->
 <!--  </div>-->
 <!-- <div>-->
    <%= link_to "Explore  ⌲", pets_path, class: "btn btn-primary mt-2" %>
  </div>
</div>
</div>

app/views/pets/_info_window_html.erb
<h2><%= pet.name %> </h2>

app/views/pets/_pet_marker.html.erb
<%# <%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/pets/index.html.erb
<div id="pets-banner">
<h1>Check out the amazing creatures available for rent!
</h1>
</div>

<div class="container">
<div class="d-flex flex-wrap">

<% @pets.each do |pet| %>
  <%= link_to pet_path(pet) do%>
  <div class="pet-card my-3 mx-3" >
    <h4><%= pet.name %></h4>
  <% if pet.photo.key != nil %>
    <%= cl_image_tag pet.photo.key, class: "index-img" %>
  <% end %>
  <div class="pet-text">
  <div class="d-flex justify-content-around">
  <p class="card-text"><strong>Species:</strong> <%= pet.species %> <p>
  <p class="card-text"><strong>Price:</strong> $<%= pet.price %></p>
</div>
</div>
</div>
  <% end %>
  <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container mt-5">
<h2>Add New Creature</h3>
  <%= simple_form_for(@pet) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :species %>
      <%= f.input :gender %>
      <%= f.input :age %>
      <%= f.input :description %>
      <%= f.input :special_notes %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>

    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/pets/show.html.erb
<div class="container mb-5 pb-5 m-auto">
<div class="mt-5">
<%= link_to pets_path do %>
  <i style='font-size:40px', class='fas fa-angle-left mt-5'></i>
  <% end %>
  <div class= "row mt-5">
    <div class="d-flex align-items-center w-75 justify-items-center m-auto">

    <div class= "col-sm">

    </div>

    </div>

  <div class="d-flex align-items-center flex-column justify-items-center">
  <div class="d-flex justify-content-around align-items-center w-50">
  <h2 class="w-50" style="color:black, text-align: center, font-weight:700, font-size: 5em"><strong><%= @pet.name %></strong></h2>
  <%= link_to "Book this creature",  new_pet_booking_path(@pet), class: "btn btn-primary" %>
  </div>
  <% if @pet.photo.key != nil %>
  <%= cl_image_tag @pet.photo.key, class: "w-50 my-2 rounded-5 border border-primary border-3 shadow", style: "object-fit: cover" %>

  <% end %>


    <div class="w-50 d-flex flex-column justify-items-center mt-3">
    <div class="d-flex justify-items-center mt-3">
    <div class="mb-3 me-5" style="width: 30%">
    <p class="text-start fs-5"><strong>Species:</strong>
    <%= @pet.species %></p>
    <p class="text-start fs-5"><strong>Age:</strong>
    <%= @pet.age %></p>
    <p class="text-start fs-5"><strong>Gender:</strong>
    <%= @pet.gender %></p>

    </div>
  <div class="mb-3 me-3" style="width: 60%">
    <p class="text-start fs-5 lh-sm"><strong>Description:</strong>
    <%= @pet.description %></p>
    <p class="text-start fs-5 lh-sm"><strong>Special Notes:</strong>
    <%= @pet.special_notes %></p>
    <p class="text-start fs-5"><strong>Price:</strong>
    $<%= @pet.price %></p>
  </div>
  </div>
  </div>
  </div>
    <div style="width: 100%">


  </div>
  </div>
  <div>
    <% if policy(@pet).edit? %>
    <%= link_to "Edit this creature", edit_pet_path(@pet) %>
    <% end %>
    <%= button_to "Remove this creature", @pet, method: :delete if policy(@pet).destroy? %>
  </div>

<h4 style="margin-left:25%"><strong>Where I'm located</strong></h4>
  <div class="mx-auto mt-4 rounded-5" style="width: 50%; height: 300px;"
   data-controller="map"
   data-map-markers-value="<%= @pet_markers.to_json %>"
   data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/users/_info_window.html.erb
<h2><%= user.first_name %> <%= user.last_name %></h2>
<p><%= user.address %></p>

app/views/users/_marker.html.erb
<%# <%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/users/show.html.erb
<div class="container my-5">
  <div class="row">
  </div>
  <h2 class="mt-5 mb-3 ms-4" style="font-size: 40px"><strong>My Profile</strong></h2>

  <div class="row mt-4">
    <div class="col-4 d-flex flex-column align-items-start justify-items-center" style="margin-left: 30px">
    <h3 class="mb-3" style="color:#68B3D9">My Info</h3>
    <div>
        <% if @user.photo.key != nil %>
          <%= cl_image_tag @user.photo.key, class: "rounded-circle shadow p-1 mb-2 bg-white rounded", style: "width: 150" %>
          <% end %>
        </div>
        <div>
          <h3><%= @user.first_name %> <%= @user.last_name %></h3>
        </div>
        <div>
          <p><strong>My email: </strong><%= @user.email %></p>
        </div>
        <div>
        <p><%= @user.bio %></p>
      </div>
        <div>
          <p><strong>My Home Address: </strong></p>
          <p><%= @user.address %></p>
        </div>
      <div class="my-3 shadow rounded-5 border border-primary border-3" style="width: 100%; height: 300px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <%= link_to "Edit my Profile", edit_user_registration_path(@user), class: "btn btn-primary mt-3"%>
    </div>
    <div style="margin-right: 30px" class="col-4 ms-3">
        <h3 class="mb-2" style="color:#68B3D9">My Creatures</h3>
        <p class="btn btn-primary mt-3 pet_button"><%=link_to "Add a New Creature", new_pet_path if policy(Pet).new?%></p>
        <% @user.pets.each do |pet| %>
          <h4 class="mb-3 mt-2"> <%= pet.name %> </h4>
          <%= link_to pet_path(pet) do%>
          <div class="mb-1 h-auto shadow pet_card rounded-5 border border-primary border-3" style="background-color: white">
          <% if pet.photo.key != nil %>
          <%= cl_image_tag pet.photo.key, class: "mb-4 bg-white rounded-bottom rounded-5 w-100 h-100", style: "object-fit: cover" %>
          <% end %>
          <p class="ms-5 w-100"> <strong>About me: </strong><%= pet.description %> </p>
          <p class="ms-5 w-100"> <strong>Species: </strong><%= pet.species %> </p>
          <p class="ms-5 w-100"> <strong>Gender:</strong> <%= pet.gender %> </p>
          <p class="ms-5 w-100"> <strong>Special Notes: </strong><%= pet.special_notes %> </p>
          <p class="ms-5 w-100 mb-5"> <strong>Listed Price: </strong>$<%= pet.price %> </p>
        <% end %>
        <% end %>
        </div>
    </div>
    <div class="col-3">
        <div>
          <h3 class="mb-4" style="color:#68B3D9">My Booking Requests</h3>
          <table class="booking-table">
            <thead>
              <tr>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @user.bookings.each do |booking| %>
                <tr>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td>
                    <% if booking.accepted? %>
                      <span class="badge badge-success">Accepted</span>
                     <% elsif booking.rejected? %>
                      <span class="badge badge-danger">Rejected</span>
                    <% else %>
                      <span class="badge badge-warning">Pending</span>
                    <% end %>
                  </td>
                  <td>
                    <% if booking.pending? %>
                      <%= link_to "Accept", accept_booking_path(booking), method: :put, class: "btn btn-sm btn-success" %>
                      <%= link_to "Reject", reject_booking_path(booking), method: :put, class: "btn btn-sm btn-success" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>